### ISSUE TITLE
style="overflow: hidden; " added to svg tag

### ISSUE THREAD

**Issue by friguzzi** [SWI-Prolog/swish#70]
Hi,
the attribute
style="overflow: hidden; "
is added to the svg tag automatically but it causes problems when rendering SLDNF trees. The overflow should be set to auto.
I added
<style>
svg:not(:root) {
    overflow: auto;
  }
</style>
but it is overwritten by
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="81pt" height="139pt" version="1.1" xmlns:ev="http://www.w3.org/2001/xml-events" style="overflow: hidden; ">
I can't understand where style="overflow: hidden; " is added in the code

Fabrizio

**Comment by friguzzi** [comment]
I found where it is set. However, that was not the problem:
when I build an SLDNF tree of a program, it is shown correctly.
If I build another one, it is shown correctly if it's the same as the previous one, otherwise it is shown incorrectly. This doesn't happen in notebooks or if I clear the answers pane.

**Comment by friguzzi** [comment]
Saving the svg opens it in a new tab and it is always shown correctly, so it must be a problem of swish

**Comment by JanWielemaker** [comment]
Bit brief (I'm traveling).  We noticed the same issue with R images and Graphviz.  In both cases the issue is that the SVG contains id=... and style statements referring to these ids.   With two images you get conflicts in the ids.  For R we implemented renaming of the IDs.  Didn't do this for Graphviz yet.  Possibly there is a completely generic way to do so, but likely this is rather complicated as it requires understanding SVG.  A specific implementation is fairly easy.

**Comment by friguzzi** [comment]
Thanks, that's the problem.
I looked at the solution for R in r_swish.pl and I'm trying to apply it to SLDNF trees but
I'm not able to call the function unique_id because node is not defined
However, node is used in 
fixIDs(svg, "N"+node.unique_id()+"_");
in r_swish.pl
By looking at runner.js, it seems to be added to all span of class output.
I tried that as well but node is still not found.
Here is the code I'm using that doesn't worl
`
svg(SVG, _Options) -->
	html([ style('svg:not(:root) {
    overflow: auto;
  }'),\[SVG],
	       \js_script({|javascript||

(function() {
   if ( $.ajaxScript ) {
     var div  = $.ajaxScript.parent();
     var svg  = div.find("svg");
     var data = { w0: svg.width(),
		  h0: svg.height()
		};
     var pan;

function fixIDs(node, prefix1) {
  var i=0;
  node.each(function() {
    var prefix = prefix1+(i++)+"_";
    var img = $(this);
    var hprefix = "#"+prefix;
    var re = /(url\()#([^)]*)(\))/;

    img.find("[id]").each(function() {
      var elem = $(this);
      elem.attr("id", prefix+elem.attr("id"));
    });
    img.find("use").each(function() {
      var elem = $(this);
      var r = elem.attr("xlink:href");
      if ( r.charAt(0) == "#" )
	elem.attr("xlink:href", hprefix+r.slice(1));
    });
    img.find("[clip-path]").each(function() {
      var elem = $(this);
      var r = elem.attr("clip-path").match(re);
      if ( r.length == 4 )
	elem.attr("clip-path", r[1]+hprefix+r[2]+r[3]);
    });
  });
}


     function updateSize() {
       var w = svg.closest("div.answer").innerWidth();

       function reactive() {
	 if ( !data.reactive ) {
	   data.reactive = true;
	   div.on("reactive-resize", updateSize);
	 }
 }

fixIDs(svg, "N"+node.unique_id()+"_");
       w = Math.max(w*0.85, 300);
       if ( w < data.w0 ) {
	 svg.width(w);
	 svg.height(w = Math.max(w*data.h0/data.w0, w/4));
	 reactive();
	 if ( pan ) {
	   pan.resize();
	   pan.fit();
	   pan.center();
	 }
       }
     }

     require(["svg-pan-zoom"], function(svgPanZoom) {
       updateSize()
       pan = svgPanZoom(svg[0], {
			  // controlIconsEnabled: true
			  maxZoom: 50
			});
    });
   }
 })();
		      |})
	     ]).

`
Any idea why?

**Comment by JanWielemaker** [comment]
Closed for lack of activity
